# Generated by Django 3.1.7 on 2021-10-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminController', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordlogin',
            name='datetime',
        ),
        migrations.AddField(
            model_name='recordlogin',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
