# Generated by Django 3.1.7 on 2021-10-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
