# Generated by Django 3.1.7 on 2021-10-04 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_exam_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='data',
            new_name='date',
        ),
    ]
